the_barber_finder/blog/urls.py
from django.urls import path, include
from .views import users_view, set_available_times, reserve_view, choose_subtime, set_av_time, reserve_time

app_name = 'blog'

urlpatterns = [
    path('', users_view, name='Users'),
    path('auth/', include('authentincation.urls')),
    path('set_av_times/', set_available_times, name="set_av_time"),
    path('set_times/', set_av_time, name="set_time"),
    path('reserve_view/', reserve_view, name='reserve_barber'),
    path('subtime/', choose_subtime, name='subtime'),
    path('reservation/', reserve_time, name='reserve_time'),
]

the_barber_finder/the_barber_finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from the_barber_finder import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_barber_finder/templates/create-store.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v4.1.1">
        <title>Signin Template · Bootstrap</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/sign-in/">

        <!-- Bootstrap core CSS -->
        <link href="../static/assets/dist/css/bootstrap.min.css" rel="stylesheet">

        <style>
            .bd-placeholder-img
            {
            	font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px)
            {
                .bd-placeholder-img-lg
                {
                    font-size: 3.5rem;
                }
            }
		</style>
		
        <link href="../static/css/signup.css" rel="stylesheet">
    </head>
	<body class="text-center d-flex flex-column">
		<img class="mb-4" src="../static/logo.png" alt="" width="400" style="margin-bottom: -75px!important;margin-top: -75px!important;">

		<form class="form-signup">
            <h1 class="h3 mb-3 font-weight-normal">Create Store</h1>
            <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
                </div>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="inputGroupFile01"
                    aria-describedby="inputGroupFileAddon01">
                  <label class="custom-file-label" for="inputGroupFile01">Upload Avatar</label>
                </div>
              </div>
			<label for="input" class="sr-only">Store Name</label>
			<input type="middlebox" id="inputUsername" class="form-control" placeholder="Store Name" style="text-align:center;" required autofocus>
			<label for="input" class="sr-only">Address</label>
            <input type="middlebox" id="input" class="form-control" placeholder="Address" style="text-align:center;" required>
            <div><br/></div>
            <div class="form-group">
                <label for="comment">Description:</label>
                <textarea class="form-control" rows="5" id="comment"></textarea>
              </div>
			<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
			<p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
		</form>
	</body>
</html>

the_barber_finder/templates/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
              integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
      <link href="{% static 'assets/dist/css/bootstrap.css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
      <link href="{% static 'css/album.css' %}" rel="stylesheet"  type="text/css">

  </head>
  <body>
    <header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg> -->
        <img class="mb-4" src="{% static 'logo.png' %}" alt=""  height="150" style="margin-left: -25px!important;margin-bottom: -75px!important;margin-top: -75px!important;">
        <!-- <strong>Barbershop</strong> -->
      </a>
      <div class="flex-grow-1">

      </div>
      <div class="username navbar-item">
        <i>Hi, {{ name }}</i>
      </div>
      <div class="btn-group">
        <button class="navbar-item btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'blog:authentication:main' %}'" type="submit" >Sign In</button>
        {% if role == "Barber" %}
        <button class="navbar-item btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'blog:authentication:main' %}'" type="submit" >Manage Store</button>
        <button class="navbar-item btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'blog:set_time' %}'" type="submit" >Set Available</button>
        {% endif %}
      </div>
        </div>
    </div>
  </div>
</header>

<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
    <h3 style="text-align: center; color: lightslategrey;  " >Barber Shops</h3>
    <div class="row">
          {% for x in shops %}
          {% csrf_token %}
              <form action="{% url 'blog:reserve_barber' %}" class="col-md-4" method="post">
              {% csrf_token %}
{#        <div class="col-md-4">#}
          <div class="card mb-4 shadow-sm">
              <img src="{{x.image.url}}" alt="" class="bd-placeholder-img card-img-top" width="100%" height="225" >
{#            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="{{x.image.url}}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>#}
              <div class="card-body">
              <p class="card-text">{{ x.name }}</p>
                  <input type="hidden" id="shop_id" name="shop_id" value= {{ x.id }}>
              <div class="d-flex justify-content-between align-items-center">
                <button type="submit" class="btn btn-sm btn-outline-secondary">Reserve</button>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
{#        </div>#}
              </form>
          {% endfor %}
            </div>

        <hr style="border-top: grey 1px dashed">
        <h3 style="text-align: center; color: lightslategrey;  " >Reserved</h3>
        <div class="row" >
        {% if role == "Barber" %}
        {% for y in reserved %}
          {% csrf_token %}
              <form action="" class="col-md-4" method="post">
              {% csrf_token %}
{#        <div class="col-md-4">#}
          <div class="card mb-4 shadow-sm">
{#              <img src="{{x.image.url}}" alt="" class="bd-placeholder-img card-img-top" width="100%" height="225" >#}
{#            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="{{x.image.url}}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>#}
              <div class="card-body">
              <p class="card-text">{{ y.customer.user.user.username }}</p>
              <p class="card-text">{{ y.date }}</p>
              <p class="card-text">{{ y.sub_time }}</p>

                  <input type="hidden" id="shop_id" name="shop_id" value= {{ x.id }}>
              <div class="d-flex justify-content-between align-items-center">
                <button type="submit" class="btn btn-sm btn-outline-secondary">Reserved</button>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
{#        </div>#}
              </form>
          {% endfor %}
        {% elif role == "Customer" %}

            {% for y in reserved %}
          {% csrf_token %}
              <form action="" class="col-md-4" method="post">
              {% csrf_token %}
{#        <div class="col-md-4">#}
          <div class="card mb-4 shadow-sm">
{#              <img src="{{x.image.url}}" alt="" class="bd-placeholder-img card-img-top" width="100%" height="225" >#}
{#            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="{{x.image.url}}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>#}
              <div class="card-body">
              <p class="card-text">{{ y.customer.user.user.username }}</p>
              <p class="card-text">{{ y.date }}</p>
              <p class="card-text">{{ y.sub_time }}</p>

                  <input type="hidden" id="shop_id" name="shop_id" value= {{ x.id }}>
              <div class="d-flex justify-content-between align-items-center">
                <button type="submit" class="btn btn-sm btn-outline-secondary">Reserved</button>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
{#        </div>#}
              </form>
          {% endfor %}

        {% endif %}
        </div>
  </div>
  </div>
</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

the_barber_finder/templates/reservation-choose-tim.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
              integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" /> 

    <!--Font Awesome (added because you use icons in your prepend/append)-->
    <link rel="stylesheet" href="https://formden.com/static/cdn/font-awesome/4.4.0/css/font-awesome.min.css" />

    <!-- Inline CSS based on choices in "Settings" tab -->
    <style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'assets/dist/css/bootstrap.css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
      <link href="{% static 'css/album.css' %}" rel="stylesheet"  type="text/css">
  </head>
  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <!-- <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg> -->
            <img class="mb-4" src="../static/logo.png" alt=""  height="150" style="margin-left: -25px!important;margin-bottom: -75px!important;margin-top: -75px!important;">
            <!-- <strong>Barbershop</strong> -->
          </a>
          <div class="flex-grow-1">

          </div>
          <div class="username">
            Name
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
{#                {{  }}#}
               {% for x in Barber %}
             <div class="col-md-6 col-sm-6 col-xs-12">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{x}}</text></svg>

      <!-- HTML Form (wrapped in a .bootstrap-iso div) -->
                <div class="bootstrap-iso">
                 <div class="container-fluid">

                <form method="post" action="{% url 'blog:subtime' %}" >
                    {% csrf_token %}
                <div class="form-group ">
                  <div><br></div>
                <label class="control-label requiredField" for="date">
                  Date
                  <span class="asteriskField">
                  *
                  </span>
                </label>
                <div class="input-group">
                  <div class="input-group-addon">
                  <i class="fa fa-calendar">
                  </i>
                  </div>
                  <input class="form-control" id="date" name="date" placeholder="YYYY-MM-DD" type="text"/>
                  <input type="hidden" id="barber_name" name="barber_name" value= {{ x }}>
                </div>
                </div>
                <div class="form-group">
                <div>
                  <button class="btn btn-primary " name="submit" type="submit">
                  Submit
                  </button>
                </div>
                </div>

              </form>
              <div>
                <p id="error">
                  
                </p>
              </div>
            </div>
            </div>
          </div>
            {% endfor %}
{#            {{ ?? }}#}
         </div>

        </div>
      </div>

      

    </main>
    <footer class="text-muted">
      <div class="container">
        <button type="button" class="btn btn-primary">Back</button>
      </div>
    </footer>
    <!-- Extra JavaScript/CSS added manually in "Settings" tab -->
    <!-- Include jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

    <script>
        $(document).ready(function(){
            var date_input=$('input[name="date"]'); //our date input has the name "date"
            var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
            date_input.datepicker({
                format: 'yyyy-mm-dd',
                container: container,
                todayHighlight: true,
                autoclose: true,
            })
        })
    </script>
  </body>
</html>

the_barber_finder/templates/subtime_reserve.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Album example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
              integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
    <!-- Special version of Bootstrap that only affects content wrapped in .bootstrap-iso -->
    <link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" /> 

    <!--Font Awesome (added because you use icons in your prepend/append)-->
    <link rel="stylesheet" href="https://formden.com/static/cdn/font-awesome/4.4.0/css/font-awesome.min.css" />

    <!-- Inline CSS based on choices in "Settings" tab -->
    <style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>

    <!-- Bootstrap core CSS -->
      <link href="{% static 'assets/dist/css/bootstrap.css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

    <script src="{% static 'css/test.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.css" rel="stylesheet"/>
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>
  <body>
    <p>{{ date }}</p>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="#" class="text-white">Follow on Twitter</a></li>
                <li><a href="#" class="text-white">Like on Facebook</a></li>
                <li><a href="#" class="text-white">Email me</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <!-- <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg> -->
            <img class="mb-4" src="../static/logo.png" alt=""  height="150" style="margin-left: -25px!important;margin-bottom: -75px!important;margin-top: -75px!important;">
            <!-- <strong>Barbershop</strong> -->
          </a>
          <div class="flex-grow-1">

          </div>
          <div class="username">
            Name
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <div class="album py-5 bg-light">
        <div class="container">
      <!-- HTML Form (wrapped in a .bootstrap-iso div) -->
          <div class="bootstrap-iso">
            <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-12">
              <form method="post" action="{% url 'blog:reserve_time' %}">
                  {% csrf_token %}
                <div class="form-group ">
                  <label class="control-label requiredField" for="number1">
                    Choose subtime
                    <span class="asteriskField">
                    *
                    </span>
                  </label>
                  <div>
                    <input type="text" id="time" name="time" placeholder="Time">
                    <input type="hidden" id="shave_date" name="shave_date" value= {{ shave_date }}>
                    <input type="hidden" id="barber_name" name="barber_name" value= {{ barber_name }}>
                  </div>
                </div>

                <div class="form-group">
                <div>
                  <button class="btn btn-primary " name="submit" type="submit">
                  Submit
                  </button>
                </div>
                </div>
              </form>
              <div>
                <p id="error">
                  
                </p>
              </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>

      

    </main>
    <!-- Extra JavaScript/CSS added manually in "Settings" tab -->
    <!-- Include jQuery -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

    <script>
      const timepicker = new TimePicker(['time'], {
      lang: 'en',
      theme: 'dark'
    });
    timepicker.on('change', function(evt) {
      
      let value = (evt.hour || '00') + ':' + (evt.minute || '00');
      evt.element.value = value;

    });

    </script>

    <script>
        $(document).ready(function(){
            var date_input=$('input[name="date"]'); //our date input has the name "date"
            var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
            date_input.datepicker({
                format: 'mm/dd/yyyy',
                container: container,
                todayHighlight: true,
                autoclose: true,
            })
        })
    </script>
  </body>
</html>